name: build goapp

on :
 workflow_dispatch:
 push:
 
  
jobs :
 build :
  runs-on : ubuntu-latest
  steps:
   - name: Checkout Source
     uses: actions/checkout@v4

   - name: Login to Docker
     run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

   - name: Build docker image
     run: docker build -t gowithgithub .

   - name: Push to Dockerhub repo
     run: docker push  gowithgithub:latest    
