name: build goapp

on :
 workflow_dispatch:
 push:
 

jobs :
 
 build :
  runs-on : ubuntu-latest
  permissions:
    packages: write
  steps:
   - name: Checkout Source
     uses: actions/checkout@v4

   - name: Docker Login
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

   - name: GHCR Login
     uses: docker/login-action@v3
     with:
       registry: ghcr.io
       username: ${{ github.repository_owner }}
       password: ${{ secrets.GITHUB_TOKEN }}
    

   - name: Build docker image
     run: docker build -t goapps .

   - name: Container registry push
     uses: docker/build-push-action@v6
     with:
       context: .
       push: true
       tags: |
        ${{ secrets.DOCKER_USERNAME}}/goapps:${{ github.sha }}
        ghcr.io/${{ github.repository_owner }}/goapps:${{ github.sha }}
