name: build goapp on selfhosted runner

on :
 workflow_dispatch:
 
 

jobs :
 
 build :
  runs-on : [self-hosted]
  permissions:
    packages: write
  steps:
   - name: Checkout Source
     uses: actions/checkout@v4
   - name: Install docker
     uses: papodaca/install-docker-action@main  

   - name: Docker Login
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Build docker image
     run: docker build -t goapps .

   - name: Run the image
     run: docker run -d -p 8080:8080 goapps:latest   
